# Generated by Django 4.1.6 on 2023-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(max_length=3000, verbose_name='описание')),
                ('status', models.CharField(choices=[('new', 'новая'), ('progress', 'процесс'), ('done', 'сделано')], default='new', max_length=10)),
                ('datetime', models.DateField(auto_now=True, verbose_name='дата изменения')),
            ],
        ),
    ]
