# Generated by Django 4.1.6 on 2023-02-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='detailed_view',
            field=models.TextField(blank=True, max_length=3500, verbose_name='детальное_описание'),
        ),
    ]
